Bump io.spring.dependency-management from 1.0.15.RELEASE to 1.1.0 in /gradle-kotlin-dsl (#11)
Bumps
[io.spring.dependency-management](https://github.com/spring-gradle-plugins/dependency-management-plugin)
from 1.0.15.RELEASE to 1.1.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/spring-gradle-plugins/dependency-management-plugin/releases">io.spring.dependency-management's
releases</a>.</em></p>
<blockquote>
<h2>v1.1.0</h2>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li>Exclusions are not applied when versions are provided by constraints
<a
href="https://github-redirect.dependabot.com/spring-gradle-plugins/dependency-management-plugin/issues/341">#341</a></li>
<li>Performance regression in 1.1.0-RC1 <a
href="https://github-redirect.dependabot.com/spring-gradle-plugins/dependency-management-plugin/issues/339">#339</a></li>
</ul>
<h2>v1.1.0-RC1</h2>
<h2>:star: New Features</h2>
<ul>
<li>Remove support for Gradle's maven plugin <a
href="https://github-redirect.dependabot.com/spring-gradle-plugins/dependency-management-plugin/issues/333">#333</a></li>
<li>Raise the minimum supported version of Java to 8 <a
href="https://github-redirect.dependabot.com/spring-gradle-plugins/dependency-management-plugin/issues/270">#270</a></li>
<li>Raise the minimum supported version of Gradle to 6.8 <a
href="https://github-redirect.dependabot.com/spring-gradle-plugins/dependency-management-plugin/issues/269">#269</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/spring-gradle-plugins/dependency-management-plugin/commit/38f0b071f910b45db0fe62e8ca3da28703b092f1"><code>38f0b07</code></a>
Release v1.1.0</li>
<li><a
href="https://github.com/spring-gradle-plugins/dependency-management-plugin/commit/ea3c3c71fd9f42d013eb9ecb0b89874c850b79a0"><code>ea3c3c7</code></a>
Merge branch '1.0.x'</li>
<li><a
href="https://github.com/spring-gradle-plugins/dependency-management-plugin/commit/55dcb51553c59b06b32e24a532757e568cbcebe7"><code>55dcb51</code></a>
Remove redundant catch of NoSuchMethodError</li>
<li><a
href="https://github.com/spring-gradle-plugins/dependency-management-plugin/commit/48f0c4d438a6a8d1f80b92df585dc0451c1bfa45"><code>48f0c4d</code></a>
Merge branch '1.0.x'</li>
<li><a
href="https://github.com/spring-gradle-plugins/dependency-management-plugin/commit/42c0a3442cbe31dcf5c9cd4851973cb9c4ff0b3d"><code>42c0a34</code></a>
Add forward merge hooks</li>
<li><a
href="https://github.com/spring-gradle-plugins/dependency-management-plugin/commit/7555595305956dede31ac16604045cb477103053"><code>7555595</code></a>
Merge branch '1.0.x'</li>
<li><a
href="https://github.com/spring-gradle-plugins/dependency-management-plugin/commit/b13fae08e1db357705aca5d493c19d5cb6b8eb04"><code>b13fae0</code></a>
Fix logic for only resolving dependency management when necessary</li>
<li><a
href="https://github.com/spring-gradle-plugins/dependency-management-plugin/commit/251d6f1c066991a59956ec9e8ea7bb9728ae0a0f"><code>251d6f1</code></a>
Merge branch '1.0.x'</li>
<li><a
href="https://github.com/spring-gradle-plugins/dependency-management-plugin/commit/4156a8a279f77ca0bd89f715d379a5449f67773d"><code>4156a8a</code></a>
Merge branch '1.0.x'</li>
<li><a
href="https://github.com/spring-gradle-plugins/dependency-management-plugin/commit/744ad82bd14ffbbb8eeb4f92c32a4b40dfe3d8f8"><code>744ad82</code></a>
Merge branch '1.0.x'</li>
<li>Additional commits viewable in <a
href="https://github.com/spring-gradle-plugins/dependency-management-plugin/compare/v1.0.15.RELEASE...v1.1.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=io.spring.dependency-management&package-manager=gradle&previous-version=1.0.15.RELEASE&new-version=1.1.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>